"""init database digram

Revision ID: eec7e20cedbb
Revises: 
Create Date: 2025-06-25 23:17:04.730442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec7e20cedbb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watermarktemplate', sa.Column('margin_x_percent', sa.Float(), nullable=False))
    op.add_column('watermarktemplate', sa.Column('margin_y_percent', sa.Float(), nullable=False))
    op.alter_column('watermarktemplate', 'position',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('TOP_LEFT', 'TOP_CENTER', 'TOP_RIGHT', 'MIDDLE_LEFT', 'MIDDLE_CENTER', 'MIDDLE_RIGHT', 'BOTTOM_LEFT', 'BOTTOM_CENTER', 'BOTTOM_RIGHT', name='positiontype'),
               existing_nullable=False)
    op.drop_column('watermarktemplate', 'margin_x')
    op.drop_column('watermarktemplate', 'margin_y')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watermarktemplate', sa.Column('margin_y', sa.INTEGER(), nullable=False))
    op.add_column('watermarktemplate', sa.Column('margin_x', sa.INTEGER(), nullable=False))
    op.alter_column('watermarktemplate', 'position',
               existing_type=sa.Enum('TOP_LEFT', 'TOP_CENTER', 'TOP_RIGHT', 'MIDDLE_LEFT', 'MIDDLE_CENTER', 'MIDDLE_RIGHT', 'BOTTOM_LEFT', 'BOTTOM_CENTER', 'BOTTOM_RIGHT', name='positiontype'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.drop_column('watermarktemplate', 'margin_y_percent')
    op.drop_column('watermarktemplate', 'margin_x_percent')
    # ### end Alembic commands ###
